# Generated by Django 4.2 on 2025-11-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('department', models.CharField(default='Government', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('accessibility_score', models.IntegerField(default=0)),
                ('security_score', models.IntegerField(default=0)),
                ('performance_score', models.IntegerField(default=0)),
                ('code_quality_score', models.IntegerField(default=0)),
                ('accessibility_issues', models.JSONField(default=dict)),
                ('security_issues', models.JSONField(default=dict)),
                ('performance_data', models.JSONField(default=dict)),
                ('code_quality_issues', models.JSONField(default=dict)),
                ('ai_recommendations', models.TextField(blank=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='analyzer.governmentportal')),
            ],
        ),
    ]
